name: Build (Windows, Clang)

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env: # CHANGE THIS selectively on targets
      CC: clang
      CXX: clang++
    
    steps:
    - uses: actions/checkout@v3
      with: { submodules: recursive }
    
    - name: Install CMake
      uses: lukka/get-cmake@v3.29.2
    
    #- name: Install compiler ${{ env.compiler.displayname }} # CHANGE THIS selectively on targets
    #  uses: ${{ env.compiler.setup }}
    
    - name: Install python
      uses: actions/setup-python@v4
      with: { python-version: '3.10' }
      
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.3
      with: { version: "16" }
      
    - name: Install Libclang
      run: python -m pip install libclang
    
    - name: Generate GLEW sources
      working-directory: SanableEngine/libs/glew/auto
      run: make

    - run: mkdir SanableEngine\builds\Win64\
    
    - name: Generate build files
      working-directory: SanableEngine/builds/Win64/
      run: cmake -S ../../ -B intermediate -G Ninja
    
    - name: Build
      working-directory: SanableEngine/builds/Win64/
      run: cmake --build intermediate
    
    - name: Package
      working-directory: SanableEngine/builds/Win64/
      run: cmake --install intermediate --prefix install

    - name: Upload build
      uses: actions/upload-artifact@v3.1.0
      with:
        path: SanableEngine/builds/Win64/install
        name: Build-Windows-Clang
