name: Build (Emscripten)

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: tot
    
    - name: Setup build script (CMake)
      working-directory: SanableEngine/
      run: |
        emcmake cmake builds/Win64/
    
    - name: Build (Ninja)
      working-directory: SanableEngine/builds/Win64
      run: ninja
      
    - name: Upload build
      uses: actions/upload-artifact@v3.1.0
      with:
        path: SanableEngine/builds/web/
        name: Build-Emscripten