name: Build (Windows)

on: workflow_dispatch

permissions:
  contents: read

env:
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1
    
    - name: Generate GLEW sources
      working-directory: SanableEngine/libs/glew/auto
      run: make

    - run: mkdir SanableEngine\builds\Win64\
    
    - name: Generate build files
      working-directory: SanableEngine/builds/Win64/
      run: cmake -S ../../ -B intermediate -G Ninja
    
    - name: Build
      working-directory: SanableEngine/builds/Win64/
      run: cmake --build intermediate
    
    - name: Package
      working-directory: SanableEngine/builds/Win64/
      run: cmake --install intermediate --prefix install

    - name: Upload build
      uses: actions/upload-artifact@v3.1.0
      with:
        path: SanableEngine/builds/Win64/install
        name: Build-Windows