name: Run all tests

on: [push, workflow_dispatch]

permissions:
  contents: read

env:
  CC: clang
  CXX: clang++

jobs:
  
  test-windows-msvc:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1
    
    # Fix SDL2_image support
    - uses: ilammy/msvc-dev-cmd@v1
    
    - run: mkdir SanableEngine\builds\Win64-MSVC
    
    - name: Generate build files
      run: cmake -S SanableEngine -B SanableEngine/builds/Win64-MSVC/intermediate -G Ninja
    
    - name: Build everything
      run: cmake --build SanableEngine/builds/Win64-MSVC/intermediate
    
    - name: Test everything
      run: ctest --test-dir SanableEngine/builds/Win64-MSVC/intermediate --output-junit test-results/Win64-MSVC.xml
    
    - name: Upload reports
      uses: actions/upload-artifact@v3.1.0
      with:
        path: test-results
        name: Test-Report-Windows-MSVC
  
  
  test-windows-mingw:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1
    
    # Fix SDL2_image support
    - uses: egor-tensin/setup-mingw@v2
    
    - run: mkdir SanableEngine\builds\Win64-MinGW
    
    - name: Generate build files
      run: cmake -S SanableEngine -B SanableEngine/builds/Win64-MinGW/intermediate -G Ninja
    
    - name: Build everything
      run: cmake --build SanableEngine/builds/Win64-MinGW/intermediate
    
    - name: Test everything
      run: ctest --test-dir SanableEngine/builds/Win64-MinGW/intermediate --output-junit test-results/Win64-MinGW.xml
    
    - name: Upload reports
      uses: actions/upload-artifact@v3.1.0
      with:
        path: test-results
        name: Test-Report-Windows-MinGW
  
  
  collate:
    runs-on: windows-latest
    
    needs: [
      test-windows-msvc,
      test-windows-mingw
    ]
    
    steps:
    - name: Get results
      uses: actions/download-artifact@v3
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: 'test-results/*.xml'
        