name: Run all tests

on: [push, workflow_dispatch]

permissions:
  contents: read

env:
  CC: clang
  CXX: clang++

jobs:
  
  build-and-test-windows:
    runs-on: windows-latest
    
    strategy:
      max-parallel: 1
      matrix:
        environment-config: [
          { name: "MSVC", setup: "ilammy/msvc-dev-cmd@v1" },
          { name: "MinGW", setup: "egor-tensin/setup-mingw@v2" }
        ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1
    
    # Fix SDL2_image support
    - uses: ${{matrix.environment-config.setup}}
    
    - run: mkdir SanableEngine\builds\Win64-${{matrix.environment-config.name}}
    
    - name: Generate build files
      working-directory: SanableEngine/builds/Win64-${{matrix.environment-config.name}}
      run: cmake -S ../../ -B intermediate -G Ninja
    
    - name: Build everything
      working-directory: SanableEngine/builds/Win64-${{matrix.environment-config.name}}
      run: cmake --build intermediate
    
    - name: Test everything
      working-directory: SanableEngine/builds/Win64-${{matrix.environment-config.name}}/intermediate
      run: ctest --output-junit /test-results/Win64-${{matrix.environment-config.name}}.xml
    
    - name: Upload reports
      uses: actions/upload-artifact@v3.1.0
      with:
        path: /test-results
        name: Test-Report-Windows-${{matrix.environment-config.name}}
  
  
  collate:
    runs-on: windows-latest
    
    steps:
    - name: Get results
      uses: actions/download-artifact@v3
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '/test-results/*.xml'
        