name: Unit Tests

on:
  push:
    branches:
    - main
    - dev
    - memory-testing
    - github-ci
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/build/build-Windows-MSVC-x86_64.yml
  
  test-windows-clang:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/build/build-Windows-Clang-x86_64.yml
  
  test-web-wasm:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/build/build-Web-Emscripten-WASM.yml
  
  collate:
    runs-on: windows-latest
    
    needs: [
      test-windows-msvc,
      #test-windows-msys,
      test-windows-clang,
      test-web-wasm
    ]
    
    steps:
    - name: Get results
      uses: actions/download-artifact@v4
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: 'test-results/*.xml'
        