name: Run all tests

on: [push, workflow_dispatch]

permissions:
  contents: read

env:
  CC: clang
  CXX: clang++

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: lukka/get-cmake@v3.26.1

    - run: mkdir SanableEngine\builds\Win64\
    
    - name: Generate build files
      working-directory: SanableEngine/builds/Win64/
      run: cmake -S ../../ -B intermediate -G Ninja
    
    - name: Build everything
      working-directory: SanableEngine/builds/Win64/
      continue-on-error: true
      run: cmake --build intermediate
    
    # FIXME use matrix [engine-rtti-test, engine-memory-test]
    # with run: ${{matrix.target}}.exe --reporters=junit --out=/test-results/${{matrix.target}}.xml
    
    - name: Test RTTI
      working-directory: SanableEngine/builds/Win64/
      continue-on-error: true
      run: engine-rtti-test.exe --reporters=junit --out=/test-results/engine-rtti-test.xml
    
    - name: Test memory
      working-directory: SanableEngine/builds/Win64/
      continue-on-error: true
      run: engine-memory-test.exe --reporters=junit --out=/test-results/engine-memory-test.xml
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '/test-results/*.xml'
        